### ISSUE TITLE
Anuvaad not translating from Gujarati to english and Kannada to english 

### ISSUE THREAD

**Issue by maneeshswm** [project-anuvaad/anuvaad#70] opened 2022-04-27 07:16 UTC
<img width="1440" alt="Screenshot 2022-04-27 at 12 33 59 PM" src="https://user-images.githubusercontent.com/104488588/165462450-7966f39d-eeaf-4125-8b0e-6b28da2f2492.png">
@surendrasinghs

**Comment by Amit2508** [comment] 2023-05-24 04:09
Check the input format: Ensure that you're providing the text to be translated in the correct format and language. Verify that the input text is in the appropriate language, such as Gujarati or Kannada, and the desired output language is English.

Verify the API or service availability: Check if the Anuvaad service or API you are using is currently operational. Visit their official website, documentation, or any other reliable sources to see if there are any known issues or service disruptions. You can also try contacting their support team for assistance.

**Comment by aravinth** [comment] 2024-05-13 17:38
![image](https://github.com/project-anuvaad/anuvaad/assets/1707796/2fdaa967-583e-4d00-93e1-03d450bb86f4)
The issue is fixed . Changes merged with master  & deployed to users env.

**Closed by aravinth** 2024-05-13 17:38 UTC
Labels: bug
